# -*- coding: utf-8 -*-
"""hello.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2rOOUzd_fLkOlgcoOL8zTq0QLQVwQb6
"""



"""Import Libraries and load dataset"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
df = pd.read_csv("/content/drive/MyDrive/dev/sample-superstore.csv", encoding='latin1')
df.head()

"""Data cleaning and aggregate sales by date"""

# Convert Order Date to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed')

# Sort by date
df = df.sort_values('Order Date')

# Keep only needed columns
df = df[['Order Date', 'Sales']]

# Remove missing values
df = df.dropna()
daily_sales = df.groupby('Order Date')['Sales'].sum().reset_index()
df.head()

"""Feature Engineering"""

daily_sales['Year'] = daily_sales['Order Date'].dt.year
daily_sales['Month'] = daily_sales['Order Date'].dt.month
daily_sales['Day'] = daily_sales['Order Date'].dt.day

# Create target shift (next day sales prediction)
daily_sales['Target'] = daily_sales['Sales'].shift(-1)

daily_sales = daily_sales.dropna()
df

"""Train model"""

features = ['Sales', 'Year', 'Month', 'Day']
X = daily_sales[features]
y = daily_sales['Target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

model = LinearRegression()
model.fit(X_train, y_train)

"""Predictions"""

y_pred = model.predict(X_test)

"""Evaluation"""

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

"""Visualization"""

plt.figure(figsize=(12,6))
plt.plot(y_test.values, label="Actual Sales")
plt.plot(y_pred, label="Predicted Sales")
plt.title("Sales Forecasting - Actual vs Predicted")
plt.legend()
plt.show()

"""Future Forecast"""

last_row = daily_sales.iloc[-1].copy()

future_predictions = []

for i in range(7):
    input_data = pd.DataFrame([[
        last_row['Sales'],
        last_row['Year'],
        last_row['Month'],
        last_row['Day']
    ]], columns=features)

    pred = model.predict(input_data)[0]
    future_predictions.append(pred)

    # update for next iteration
    last_row['Sales'] = pred

"""Ploting future forecast"""

plt.figure(figsize=(10,5))
plt.plot(future_predictions, marker='o')
plt.title("Next 7 Days Sales Forecast")
plt.xlabel("Days")
plt.ylabel("Sales")
plt.show()